package roleenhance

import (
	"context"
	"fmt"
	"sort"
)

type Advisor interface {
	Recommend(context.Context, CurrentState, Evidence) (ReviewPlan, error)
}

type EnhanceService struct{ Advisor Advisor }

func (s EnhanceService) Review(ctx context.Context, root string) (CurrentState, ReviewPlan, error) {
	current, err := LoadCurrentState(root)
	if err != nil {
		return CurrentState{}, ReviewPlan{}, err
	}
	if current.Project.GeneratedBy != "promptgrinder discover" {
		return CurrentState{}, ReviewPlan{}, fmt.Errorf("missing discovery configuration: .promptgrinder/project.yaml was not generated by promptgrinder discover")
	}
	if s.Advisor == nil {
		return CurrentState{}, ReviewPlan{}, fmt.Errorf("role advisor runtime is not configured")
	}
	collectors := []interface {
		Collect(string) (Evidence, error)
	}{RepositoryContextCollector{}, DocumentationCollector{}, SkillCollector{}}
	var evidence Evidence
	for _, collector := range collectors {
		part, e := collector.Collect(root)
		if e != nil {
			return CurrentState{}, ReviewPlan{}, e
		}
		evidence.Sources = append(evidence.Sources, part.Sources...)
		evidence.Facts = append(evidence.Facts, part.Facts...)
		evidence.TotalBytes += part.TotalBytes
	}
	evidence = normalizedEvidence(evidence)
	// A file may intentionally be visible to more than one collector. Keep the
	// kind-distinct source records, but remove exact duplicates.
	evidence.Sources = dedupeSources(evidence.Sources)
	plan, err := s.Advisor.Recommend(ctx, current, evidence)
	return current, plan, err
}

func dedupeSources(in []EvidenceSource) []EvidenceSource {
	out := in[:0]
	seen := map[string]bool{}
	for _, s := range in {
		k := string(s.Kind) + "\x00" + s.Path
		if !seen[k] {
			seen[k] = true
			out = append(out, s)
		}
	}
	sort.SliceStable(out, func(i, j int) bool {
		if out[i].Path != out[j].Path {
			return out[i].Path < out[j].Path
		}
		return out[i].Kind < out[j].Kind
	})
	return out
}
